<?php

return [

    'Alaba',
    'Albacete',
    'Alacant',
    'Almería',
    'Ávila',
    'Badajoz',
    'Illes Balears',
    'Barcelona',
    'Burgos',
    'Cáceres',
    'Cádiz',
    'Castelló',
    'Ciudad Real',
    'Córdoba',
    'A Coruña',
    'Cuenca',
    'Girona',
    'Granada',
    'Guadalajara',
    'Gipuzkoa',
    'Huelva',
    'Huesca',
    'Jaén',
    'León',
    'Lleida',
    'La Rioja',
    'Lugo',
    'Madrid',
    'Málaga',
    'Murcia',
    'Navarra',
    'Ourense',
    'Asturias',
    'Palencia',
    'Las Palmas',
    'Pontevedra',
    'Salamanca',
    'Santa Cruz de Tenerife',
    'Cantabria',
    'Segovia',
    'Sevilla',
    'Soria',
    'Tarragona',
    'Teruel',
    'Toledo',
    'València',
    'Valladolid',
    'Bizkaia',
    'Zamora',
    'Zaragoza',
    'Ceuta',
    'Melilla',

];